from . import support
from . import support_call
from . import help
from . import start
from . import admin_panel
from . import purchase
from . import direction_add
from . import online_shop
from . import one_list_site
from . import promote_site
from . import site_info
from . import support_site
from . import telegramBot_info
from . import echo
